// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fgOQa9S3_BWLv0TKukclIIo-b8MaQjc',
    appId: '1:761017450319:web:5664ca82592d283e8c0f3a',
    messagingSenderId: '761017450319',
    projectId: 'hypnotic-trees-328016',
    authDomain: 'hypnotic-trees-328016.firebaseapp.com',
    storageBucket: 'hypnotic-trees-328016.appspot.com',
    measurementId: 'G-MW7B6FFSV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpo3ZnN__iQdXNXzDk-WHW-Bp7WH-HHKQ',
    appId: '1:761017450319:android:5b405f30394eb1a88c0f3a',
    messagingSenderId: '761017450319',
    projectId: 'hypnotic-trees-328016',
    storageBucket: 'hypnotic-trees-328016.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnaxVxnnA9PjBDfD2jutNwJLzjRQ5pR_w',
    appId: '1:761017450319:ios:73df6d470e97581a8c0f3a',
    messagingSenderId: '761017450319',
    projectId: 'hypnotic-trees-328016',
    storageBucket: 'hypnotic-trees-328016.appspot.com',
    iosClientId: '761017450319-tjdjh629t30v8u8pubvp67kb1g3ejv5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.karbonbasar4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnaxVxnnA9PjBDfD2jutNwJLzjRQ5pR_w',
    appId: '1:761017450319:ios:73df6d470e97581a8c0f3a',
    messagingSenderId: '761017450319',
    projectId: 'hypnotic-trees-328016',
    storageBucket: 'hypnotic-trees-328016.appspot.com',
    iosClientId: '761017450319-tjdjh629t30v8u8pubvp67kb1g3ejv5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.karbonbasar4',
  );
}
